root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
args_bin = []
bin = "bin/go-template-hot"
cmd = "go build -gcflags='all=-N -l' -o ./bin/go-template-hot ."
delay = 1000
exclude_dir = ["assets", "bin", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "dlv exec --accept-multiclient --log --headless --continue --listen :2345 --api-version 2 ./bin/go-template-hot"
include_dir = []
include_ext = ["go", "html"]
include_file = []
kill_delay = "10s"
log = "build-errors.log"
# fsnotify doesn't work in containers on Windows, so we have to poll
poll = true
poll_interval = 500
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clean_on_rebuild = false
keep_scroll = true
